spring:
  application:
    name: featureflag-service


  datasource:
    url: jdbc:mysql://localhost:3306/feature_flag_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8080

jwt:
  secret: mySuperSecretFeatureFlagKeyForJwtGeneration123456
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG